name: CI/CD
on:
 workflow_dispatch:
 push:
  branches:
   -main
jobs:
 build:
  runs-on: windows-latest
  steps:
  - uses: actions/checkout@v1
  - name: Build
    run: |
     npm install
     npm run build
  - name: Firebase Deploy
    run: |
     npm install -g firebase-tools
     firebase deploy --token ${{secrets.FIREBASE_TOKEN}}
